# Generated by Django 4.1.3 on 2022-11-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('Blue', 'Blue'), ('Grey', 'Grey'), ('Yellow', 'Yellow')], max_length=6),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('Convertible', 'Convertible'), ('Hatch', 'Hatch'), ('Sedan', 'Sedan')], max_length=11),
        ),
    ]
